project_id = "eojgjfefbjhslyeodcls"

[functions.create-client-account]
verify_jwt = false

[functions.analyze-documents]
verify_jwt = false

[functions.tjpr-monitor]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.verify-role]
verify_jwt = false